### PR TITLE
Enable dark theme toggle

### PR DESCRIPTION
**Pull request by Shmew**
So I don't go blind

### CODE REVIEW

**Comment by matthewcrews** [comment]
@Shmew Well, this is merged but the toggle isn't showing up. It's working when I run it locally.

**Comment by matthewcrews** [comment]
@Shmew I see the problem. There's a `Docs` directory and a `docs` directory. I can't figure out how to delete the `Docs` directory because Windows doesn't see it for some reason.

**Comment by Shmew** [comment]
oh wow I hadn't ever seen that happen before. I think you can fix it with `git rm Docs`.

**Comment by matthewcrews** [comment]
Thanks! That's what did it. Dark Mode should be there now. I nuked them both and then put the correct one back just to be sure.

**Pull request merged**
